### ISSUE TITLE
Is there any documentation anywhere?

### ISSUE THREAD

**Issue by Taazar** [galobtter/libSettings#10]
Hi, I was looking to use this for a user script I'm writing however I can't find any documentation or what parameters or options are available so currently I'm just cannibalising the code from Shortdesc-helper and the file in master/test/demo.js Is there any documentation or a list of available parameters written up somewhere?

**Comment by mmiyer** [comment]
Hi - appreciate someone else wanting to use this! I definitely intended this to be used by other scripts when I wrote it, but I lost motivation to document and do all the things that would allow me to advertise this for use by other people. You can still use it, but I don't have the time to maintain or document this beyond it being it used in shortdesc helper. I think shortdesc helper does use all the parameters and stuff that libSettings has, so it should be a good reference for you.
